# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: svc.proto
# plugin: harness.cli.generate
from dataclasses import dataclass

import harness.wires.asyncpg.v1
import harness.wires.grpclib.v1

from svc_pb2 import Configuration


@dataclass
class WiresOut:
    listen: harness.wires.grpclib.v1.Server


@dataclass
class WiresIn:
    __config__: Configuration
    __wires_out_type__ = WiresOut
    db: harness.wires.asyncpg.v1.Connection
    taskqueue: harness.wires.grpclib.v1.Channel
