# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: pulsar.proto
# plugin: harness.plugin.python
import sys

from harness.runtime import Runner

import pulsar
import pulsar_pb2
import pulsar_wires

runner = Runner(
    pulsar_pb2.Configuration,
    pulsar_wires.WiresIn,
    pulsar_wires.WiresOut,
)

if __name__ == '__main__':
    sys.exit(runner.run(pulsar.setup, sys.argv))
