# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: pulsar.proto
# plugin: harness.cli.generate
from dataclasses import dataclass

import harness.wires.apscheduler
import harness.wires.logging

from pulsar_pb2 import Configuration


@dataclass
class WiresOut:
    scheduler: harness.wires.apscheduler.SchedulerWire


@dataclass
class WiresIn:
    __config__: Configuration
    __wires_out_type__ = WiresOut
    redis_job_store: harness.wires.apscheduler.RedisJobStoreWire
    console: harness.wires.logging.ConsoleWire
