# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: harness/options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='harness/options.proto',
  package='harness',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x15harness/options.proto\x12\x07harness\x1a google/protobuf/descriptor.proto:-\n\x05input\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x0f \x01(\t:.\n\x06output\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x0f \x01(\t'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


INPUT_FIELD_NUMBER = 2001
input = _descriptor.FieldDescriptor(
  name='input', full_name='harness.input', index=0,
  number=2001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
OUTPUT_FIELD_NUMBER = 2002
output = _descriptor.FieldDescriptor(
  name='output', full_name='harness.output', index=1,
  number=2002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['input'] = input
DESCRIPTOR.extensions_by_name['output'] = output
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(input)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(output)

# @@protoc_insertion_point(module_scope)
