# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: scotty.proto
# plugin: harness.plugin.python
import sys

from harness.runtime import Runner

import scotty
import scotty_pb2
import scotty_wires

runner = Runner(
    scotty_pb2.Configuration,
    scotty_wires.WiresIn,
    scotty_wires.WiresOut,
)

if __name__ == '__main__':
    sys.exit(runner.run(scotty.setup, sys.argv))
