# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: scotty.proto
# plugin: harness.plugin.main
from dataclasses import dataclass

import harness.wires.asyncpg
import harness.wires.grpclib
import harness.wires.logging
import harness.wires.opentelemetry.ext.jaeger
import harness.wires.prometheus

import scotty_pb2


@dataclass
class WiresIn:
    config: scotty_pb2.Configuration
    db: harness.wires.asyncpg.PoolWire
    console: harness.wires.logging.ConsoleWire
    syslog: harness.wires.logging.SyslogWire
    tracing: harness.wires.opentelemetry.ext.jaeger.JaegerSpanExporterWire


@dataclass
class WiresOut:
    server: harness.wires.grpclib.ServerWire
    prometheus: harness.wires.prometheus.ServerWire
