# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: spock/service.proto
# plugin: harness.plugin.python
from typing import Optional
from dataclasses import dataclass

import harness.wires.logging


@dataclass
class WiresIn:
    console: Optional[harness.wires.logging.ConsoleWire]


@dataclass
class WiresOut:
    pass
