# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spock/service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from harness import wire_pb2 as harness_dot_wire__pb2
from harness import logging_pb2 as harness_dot_logging__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='spock/service.proto',
  package='spock',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13spock/service.proto\x12\x05spock\x1a\x12harness/wire.proto\x1a\x15harness/logging.proto\"\xba\x01\n\rConfiguration\x12Q\n\x07\x63onsole\x18\x03 \x01(\x0b\x32\x18.harness.logging.ConsoleB&\x8a}#\n!harness.wires.logging.ConsoleWire:V\x8a}\x07\n\x05spock\x8a} \x12\x1e\n\x1cregistry.acme.dev/team/spock\x8a}\x13\x12\x11\x12\x0f\n\r\n\x04\x33\x30\x30m\x12\x05\x31\x32\x38Mi\x8a}\x10\x12\x0e\x12\x0c\x12\n\n\x01\x31\x12\x05\x31\x36\x30Mib\x06proto3'
  ,
  dependencies=[harness_dot_wire__pb2.DESCRIPTOR,harness_dot_logging__pb2.DESCRIPTOR,])




_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='spock.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='console', full_name='spock.Configuration.console', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\212}#\n!harness.wires.logging.ConsoleWire', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\212}\007\n\005spock\212} \022\036\n\034registry.acme.dev/team/spock\212}\023\022\021\022\017\n\r\n\004300m\022\005128Mi\212}\020\022\016\022\014\022\n\n\0011\022\005160Mi',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=260,
)

_CONFIGURATION.fields_by_name['console'].message_type = harness_dot_logging__pb2._CONSOLE
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATION,
  '__module__' : 'spock.service_pb2'
  # @@protoc_insertion_point(class_scope:spock.Configuration)
  })
_sym_db.RegisterMessage(Configuration)


_CONFIGURATION.fields_by_name['console']._options = None
_CONFIGURATION._options = None
# @@protoc_insertion_point(module_scope)
