# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: kirk.proto
# plugin: harness.plugin.python
from dataclasses import dataclass

import harness.wires.aiohttp
import harness.wires.aiomonitor
import harness.wires.asyncpg
import harness.wires.grpclib
import harness.wires.logging
import harness.wires.opentelemetry

import kirk_pb2


@dataclass
class WiresIn:
    config: kirk_pb2.Configuration
    db: harness.wires.asyncpg.PoolWire
    scotty: harness.wires.grpclib.ChannelWire
    console: harness.wires.logging.ConsoleWire
    tracing: harness.wires.opentelemetry.JaegerSpanExporterWire


@dataclass
class WiresOut:
    server: harness.wires.aiohttp.ServerWire
    monitor: harness.wires.aiomonitor.MonitorWire
