# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: svc.proto
# plugin: harness.cli.generate
from dataclasses import dataclass

import harness.wires.aiohttp
import harness.wires.asyncpg
import harness.wires.logging

from svc_pb2 import Configuration


@dataclass
class WiresOut:
    listen: harness.wires.aiohttp.ServerWire


@dataclass
class WiresIn:
    __config__: Configuration
    __wires_out_type__ = WiresOut
    db: harness.wires.asyncpg.ConnectionWire
    console: harness.wires.logging.ConsoleWire
