# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: mccoy.proto
# plugin: harness.plugin.python
from dataclasses import dataclass

import harness.wires.logging
import harness.wires.uvicorn


@dataclass
class WiresIn:
    console: harness.wires.logging.ConsoleWire


@dataclass
class WiresOut:
    server: harness.wires.uvicorn.ServerWire
