name: Check
on:
- push
- pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/tox.txt') }}-${{ hashFiles('requirements/check.txt') }}
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: pip3 install -r requirements/tox.txt
    - run: tox -e black
